version: '3.8'

services:
  backend:
    build:
      context: ./sensai-ai
      dockerfile: Dockerfile
      args:
        - GOOGLE_CLIENT_ID=your_google_client_id_here
        - OPENAI_API_KEY=your_openai_api_key_here
        - ENV=development
        - S3_BUCKET_NAME=
        - S3_FOLDER_NAME=
        - BUGSNAG_API_KEY=
        - SLACK_USER_SIGNUP_WEBHOOK_URL=
        - SLACK_COURSE_CREATED_WEBHOOK_URL=
        - SLACK_USAGE_STATS_WEBHOOK_URL=
        - PHOENIX_ENDPOINT=
        - PHOENIX_API_KEY=
    working_dir: /src
    command: bash -c "python /src/startup.py && uvicorn api.main:app --host 0.0.0.0 --port 8001 --reload"
    ports:
      - "8000:8001"  # Expose backend on localhost:8000 as requested
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - sensai-local

  frontend:
    build:
      context: ./sensai-frontend
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
        - NEXTAUTH_URL=http://localhost:3000
        - NEXTAUTH_SECRET=your_nextauth_secret_here
        - BACKEND_URL=http://localhost:8000
        - NEXT_PUBLIC_BACKEND_URL=http://localhost:8000
        - NEXT_PUBLIC_APP_URL=http://localhost:3000
        - GOOGLE_CLIENT_ID=your_google_client_id_here
        - GOOGLE_CLIENT_SECRET=your_google_client_secret_here
        - JUDGE0_API_URL=LINK_TO_JUDGE0_API
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - sensai-local

networks:
  sensai-local:
    driver: bridge